name: dart_journal_domain
description: Domain layer of the Flutter journaling app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.4

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
