name: flutter_journal_presentation
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dart_journal_data:
    path: ../dart_journal_data
  dart_journal_domain:
    path: ../dart_journal_domain
  flutter:
    sdk: flutter
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: