name: dart_journal_data
description: Data layer of the Flutter journaling app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.4

dependencies:
   dart_journal_domain:
    path: ../dart_journal_domain
   logging: ^1.2.0
   path: ^1.9.0
   sqflite: ^2.3.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
